###############################################################
# Copyright (c) 2021-2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
###############################################################

keycloak:
  replicaCount: 1
  ingress:
    enabled: true
    ingressClassName: "nginx"
    # -- Provide default path for the ingress record.
    hostname: "centralidp.example.org"
    annotations:
      # -- Enable TLS configuration for the host defined at `ingress.hostname` parameter;
      # TLS certificates will be retrieved from a TLS secret with name: `{{- printf "%s-tls" .Values.ingress.hostname }}`;
      # Provide the name of ClusterIssuer to acquire the certificate required for this Ingress
      nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
      nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
      nginx.ingress.kubernetes.io/cors-allow-origin: "https://centralidp.example.org"
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
      nginx.ingress.kubernetes.io/proxy-buffering: "on"
      nginx.ingress.kubernetes.io/proxy-buffers-number: "20"
      nginx.ingress.kubernetes.io/use-regex: "true"
    tls: false

secrets:
  auth:
    existingSecret:
      adminpassword: ""
      managementpassword: ""
  postgresql:
    auth:
      existingSecret:
        postgrespassword: ""
        password: ""
        replicationPassword: ""
